const INSTRUMENTS = [
  {
    id: "hisse-senedi",
    name: "Hisse Senedi",
    shortDesc: "Borsada işlem gören şirket payları",
    category: "Sermaye Piyasası",
    risk: 4,
    liquidity: "Yüksek",
    minAmount: "Tek lot (değişken)",
    returnType: "Temettü + fiyat artışı",
    tax: "Stopaj + beyan (koşullu)",
    icon: "📈",
    description: "Hisse senedi, bir anonim şirketin ortaklık payını temsil eden menkul kıymettir. Borsa İstanbul'da (BIST) işlem görür. Yatırımcı hem şirketin kârından temettü alabilir hem de hisse fiyatı yükseldiğinde satış kârı elde edebilir. BIST 100 endeksi, kurum hedeflerine göre 2026'da 15.000-17.000 aralığına işaret etmektedir. Dezenflasyon ve faiz indirimleriyle bankacılık, GYO, perakende ve savunma sektörlerinin öne çıkması beklenmektedir.",
    pros: ["Yüksek getiri potansiyeli", "Temettü geliri", "Kolay alım-satım", "Şirket büyümesine ortak olma", "1 yıl+ elde tutulan hissede vergi muafiyeti"],
    cons: ["Fiyat dalgalanması yüksek", "Şirket iflas riski", "Piyasa bilgisi gerektirir", "Duygusal karar riski", "Enflasyon muhasebesi nedeniyle bilanço okuması karmaşık"],
    suitableFor: "Orta-uzun vadeli düşünen, risk toleransı yüksek yatırımcılar",
    notSuitableFor: "Kısa vadeli spekülasyon yapmak isteyenler, duygusal karar vermeye yatkın yatırımcılar",
    commonMistakes: ["Duygusal alım-satım yapmak", "Tek bir hisseye aşırı odaklanmak", "Panik satışı yapmak", "Temel analiz yapmadan hisse seçmek"],
    regulator: "SPK / BIST",
    methods: [
      {
        name: "Aracı Kurum (Online)",
        description: "SPK lisanslı aracı kurumlarda hesap açarak bilgisayar veya mobil uygulama üzerinden BIST'te işlem yapılır. En yaygın yöntemdir.",
        minAmount: "1 lot (şirkete göre değişir)",
        liquidity: "Çok Yüksek",
        cost: "Komisyon (%0,1–0,3)",
        tax: "Temettüde stopaj; satışta koşullu muafiyet",
        storage: "Elektronik — saklama gerekmez",
        ease: "Kolay",
        pros: ["Düşük komisyon", "Anlık işlem", "Geniş hisse seçeneği"],
        cons: ["Piyasa bilgisi gerekir", "Duygusal işlem riski"],
      },
      {
        name: "Banka Yatırım Kanalı",
        description: "Mevcut bankanızın yatırım bölümü veya internet şubesi üzerinden aracı kurum entegrasyonu ile hisse alım-satımı.",
        minAmount: "Bankaya göre değişir",
        liquidity: "Yüksek",
        cost: "Komisyon + banka masrafı",
        tax: "Aynı vergi kuralları",
        storage: "Elektronik",
        ease: "Çok Kolay",
        pros: ["Tek uygulamada banka + borsa", "Tanıdık arayüz", "Hızlı para transferi"],
        cons: ["Hisse seçeneği sınırlı olabilir", "Komisyon biraz yüksek olabilir"],
      },
      {
        name: "Robo-Danışman / Fon Sepeti",
        description: "Algoritma veya hazır portföy ile hisse ağırlıklı fon/yatırım paketi satın alma. Doğrudan tek hisse seçimi yerine paket yaklaşımı.",
        minAmount: "Düşük (bazıları 100 TL'den)",
        liquidity: "Orta",
        cost: "Yönetim ücreti + komisyon",
        tax: "Fon stopajı uygulanabilir",
        storage: "Elektronik",
        ease: "Çok Kolay",
        pros: ["Hisse seçimi bilgisi gerekmez", "Otomatik çeşitlendirme", "Disiplinli yatırım"],
        cons: ["Doğrudan hisse sahipliği değil", "Yönetim ücreti", "Özelleştirme sınırlı"],
      },
    ],
  },
  {
    id: "tahvil-bono",
    name: "Tahvil & Bono",
    shortDesc: "Devlet veya şirket borçlanma kağıtları",
    category: "Sabit Getirili",
    risk: 2,
    liquidity: "Orta",
    minAmount: "Nominal değere göre değişir",
    returnType: "Sabit veya değişken faiz",
    tax: "Stopaj (%0–%15 arası türüne göre)",
    icon: "🏛️",
    description: "Tahvil ve bonolar borçlanma araçlarıdır. Devlet tahvilleri (DİBS) devlet tarafından, özel sektör tahvilleri şirketler tarafından ihraç edilir. Belirli vade sonunda anapara ve faiz ödenir. 2026'da CDS primindeki düşüş ve yabancı yatırımcı girişleriyle DİBS faizlerinin mevcut %30'dan %25-26 seviyelerine gerilemesi beklenmektedir. Dezenflasyon süreci ve TCMB faiz indirimleri tahvil fiyatlarını desteklemektedir.",
    pros: ["Öngörülebilir getiri", "Devlet tahvillerinde düşük risk", "Portföy çeşitliliği", "Farklı vade seçenekleri"],
    cons: ["Enflasyon riski", "Faiz değişimine duyarlılık", "Erken satışta zarar", "Getiri sınırlı"],
    suitableFor: "Düşük-orta risk profilli, düzenli gelir isteyen yatırımcılar",
    notSuitableFor: "Yüksek getiri arayan, kısa vadeli spekülatif yatırımcılar",
    commonMistakes: ["Faiz değişimlerini takip etmemek", "Vade uyumunu gözetmemek", "Enflasyon riskini hesaba katmamak"],
    regulator: "Hazine ve Maliye / SPK",
    methods: [
      {
        name: "Banka",
        description: "Banka şubesi veya internet bankacılığı üzerinden devlet tahvili ve bono alımı. Hazine ihalelerine veya ikincil piyasadan erişim.",
        minAmount: "Genelde düşük nominal",
        liquidity: "Orta",
        cost: "Spread + işlem masrafı",
        tax: "Stopaj (vade ve türe göre)",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Güvenilir", "Kolay erişim", "Danışman desteği"],
        cons: ["Spread yüksek olabilir", "Vade seçeneği sınırlı"],
      },
      {
        name: "Aracı Kurum",
        description: "Borsada işlem gören tahviller ve Hazine bonoları aracı kurum platformu üzerinden alınır.",
        minAmount: "1 lot",
        liquidity: "Yüksek (borsada)",
        cost: "Komisyon",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Şeffaf fiyat", "İkincil piyasa likiditesi", "Geniş seçenek"],
        cons: ["Hesap açmak gerekir", "Bono/tahvil bilgisi gerekir"],
      },
      {
        name: "Hazine Doğrudan Satış",
        description: "Hazine ve Maliye Bakanlığı'nın bireysel yatırımcılara yönelik doğrudan satış platformları (ebebek vb.) üzerinden DİBS alımı.",
        minAmount: "Platforma göre",
        liquidity: "Düşük (vadeye kadar)",
        cost: "Düşük / komisyonsuz",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Aracısız alım", "Düşük maliyet", "Devlet güvencesi"],
        cons: ["Platform erişimi sınırlı olabilir", "Erken satış zor"],
      },
    ],
  },
  {
    id: "eurobond",
    name: "Eurobond",
    shortDesc: "Yurt dışında ihraç edilen devlet tahvilleri",
    category: "Sabit Getirili",
    risk: 3,
    liquidity: "Orta",
    minAmount: "Genelde 1.000 USD/EUR nominal",
    returnType: "Döviz cinsinden kupon faizi",
    tax: "Stopaj uygulanır",
    icon: "🌍",
    description: "Eurobond, Türkiye Cumhuriyeti'nin yurt dışında döviz cinsinden ihraç ettiği uzun vadeli tahvillerdir. Genellikle ABD doları veya avro cinsindendir.",
    pros: ["Döviz getirisi", "Uzun vade seçenekleri", "Devlet garantisi", "Portföy çeşitliliği"],
    cons: ["Kur riski", "Döviz erişimi gerekir", "Likidite sınırlı olabilir", "Global faiz etkisi"],
    suitableFor: "Döviz birikimi olan, orta vadeli düşünen yatırımcılar",
    notSuitableFor: "TL bazlı küçük yatırımcılar, döviz geliri olmayanlar",
    commonMistakes: ["Kur riskini göz ardı etmek", "Minimum tutarı karşılayamamak", "Vade sonunu beklemeden satmak"],
    regulator: "Hazine ve Maliye",
    methods: [
      {
        name: "Banka",
        description: "Döviz hesabınız üzerinden banka aracılığıyla Eurobond alımı. Genelde büyük bankaların yatırım birimleri üzerinden.",
        minAmount: "1.000 USD/EUR civarı",
        liquidity: "Orta",
        cost: "Spread + işlem masrafı",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Güvenilir", "Döviz hesabı entegrasyonu", "Danışmanlık"],
        cons: ["Yüksek minimum tutar", "Spread maliyeti"],
      },
      {
        name: "Aracı Kurum",
        description: "Uluslararası tahvil piyasasına erişimi olan aracı kurumlar üzerinden Eurobond alım-satımı.",
        minAmount: "1.000 USD/EUR",
        liquidity: "Orta–Yüksek",
        cost: "Komisyon + spread",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Rekabetçi fiyat", "İkincil piyasa", "Farklı vadeler"],
        cons: ["Döviz hesabı şart", "Minimum tutar yüksek"],
      },
    ],
  },
  {
    id: "yatirim-fonlari",
    name: "Yatırım Fonları",
    shortDesc: "Profesyonel yönetilen kolektif yatırım araçları",
    category: "Fon",
    risk: 3,
    liquidity: "Yüksek",
    minAmount: "Fon türüne göre (genelde düşük)",
    returnType: "Fon performansına bağlı",
    tax: "Stopaj (fon türüne göre değişir)",
    icon: "📊",
    description: "Yatırım fonları, birçok yatırımcının paralarını bir araya getirerek profesyonel portföy yöneticileri tarafından yönetilen araçlardır. Hisse, tahvil, altın, döviz gibi farklı varlıklara yatırım yapabilirler. Temmuz 2025 itibarıyla fon stopaj oranları %10-17,5 arasına yükseltilmiştir. Hisse fonlarında %10, tahvil ve para piyasası fonlarında %15, diğer fonlarda %17,5 stopaj uygulanır. TEFAS platformu tüm fonları tek yerden karşılaştırma imkânı sunar.",
    pros: ["Profesyonel yönetim", "Kolay çeşitlendirme", "Düşük giriş tutarı", "Geniş fon seçeneği", "TEFAS ile tek platformda karşılaştırma"],
    cons: ["Yönetim ücreti (yıllık %0,5-2)", "Performans garantisi yok", "Fon türü seçimi önemli", "Stopaj kesintisi (%10-17,5)"],
    suitableFor: "Bireysel portföy yönetmek istemeyen, çeşitlendirme arayan yatırımcılar",
    notSuitableFor: "Doğrudan varlık sahibi olmak isteyenler, düşük maliyet arayanlar",
    commonMistakes: ["Yönetim ücretlerini karşılaştırmamak", "Fon türünü anlamadan almak", "Kısa vadede sık sık fon değiştirmek"],
    regulator: "SPK / TEFAS",
    methods: [
      {
        name: "Banka",
        description: "Banka şubesi veya mobil bankacılık üzerinden fon alımı. Bankanın sunduğu fon portföyünden seçim yapılır.",
        minAmount: "Genelde 100–500 TL",
        liquidity: "Yüksek (T+1–2)",
        cost: "Yönetim ücreti (yıllık %0,5–2)",
        tax: "Stopaj (fon türüne göre %10–17,5)",
        storage: "Elektronik",
        ease: "Çok Kolay",
        pros: ["Tanıdık kanal", "Hızlı işlem", "Danışman desteği"],
        cons: ["Fon seçeneği sınırlı", "Yönetim ücreti"],
      },
      {
        name: "Aracı Kurum",
        description: "Aracı kurum platformu üzerinden geniş fon yelpazesine erişim. TEFAS fonları dahil.",
        minAmount: "Fona göre değişir",
        liquidity: "Yüksek",
        cost: "Yönetim ücreti",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Geniş fon seçeneği", "Karşılaştırma kolay", "Düşük minimum"],
        cons: ["Fon seçimi bilgisi gerekir", "Yönetim ücreti"],
      },
      {
        name: "TEFAS Platformu",
        description: "Türkiye Elektronik Fon Alım Satım Platformu — tüm TEFAS üyesi fonları tek yerden karşılaştırıp alabilirsiniz.",
        minAmount: "Fona göre (genelde düşük)",
        liquidity: "Yüksek",
        cost: "Sadece yönetim ücreti",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Tüm fonlar tek platformda", "Şeffaf karşılaştırma", "Düşük maliyet"],
        cons: ["Ayrı hesap gerekebilir", "Arayüz teknik olabilir"],
      },
    ],
  },
  {
    id: "bes",
    name: "Bireysel Emeklilik (BES)",
    shortDesc: "Uzun vadeli emeklilik birikimi",
    category: "Fon",
    risk: 2,
    liquidity: "Düşük",
    minAmount: "Aylık katkı payı (düşük)",
    returnType: "Fon getirisi + devlet katkısı",
    tax: "Emeklilikte vergi avantajı",
    icon: "🏦",
    description: "Bireysel Emeklilik Sistemi (BES), emeklilik dönemine birikim yapmayı teşvik eden uzun vadeli bir sistemdir. Devlet katkısı %30'a kadar (her yıl bütçe ile belirlenir) sağlar, yıllık üst limit 12.000 TL devlet katkısıdır (2026). Fonlar arasında seçim yapılabilir. Erken çıkışta (56 aydan önce) devlet katkısının tamamı ve getirileri iade edilmez; 56 aydan sonra kademeli hak ediş vardır. Emeklilikte stopaj oranı %0-5 arasındadır. Vergi avantajı: ödenen katkı payları gelir vergisi beyannamesinde indirim konusu yapılabilir.",
    pros: ["Devlet katkısı (yıllık 12.000 TL'ye kadar %30)", "Vergi avantajı (katkı payı indirimi)", "Disiplinli birikim", "Fon seçeneği"],
    cons: ["Uzun vade zorunluluğu (en az 56 ay)", "Erken çıkışta devlet katkısı kaybı", "Fon performans riski", "Enflasyon etkisi", "Yönetim gider kesintisi (%1-2)"],
    suitableFor: "Emeklilik planı yapan, uzun vadeli birikim hedefleyenler",
    notSuitableFor: "Kısa vadeli yatırımcılar, paraya hızlı erişim ihtiyacı olanlar",
    commonMistakes: ["Erken çıkışta kesintileri hesaba katmamak", "Fon dağılımını hiç değiştirmemek", "Sadece devlet katkısına odaklanmak"],
    regulator: "SPK / EGM",
    methods: [
      {
        name: "Emeklilik Şirketi",
        description: "Doğrudan emeklilik şirketinin web sitesi veya çağrı merkezi üzerinden BES sözleşmesi açma.",
        minAmount: "Aylık ~500 TL civarı",
        liquidity: "Düşük (56 ay kuralı)",
        cost: "Yönetim gider kesintisi",
        tax: "Emeklilikte avantajlı",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Geniş fon seçeneği", "Doğrudan iletişim", "Devlet katkısı"],
        cons: ["Uzun vade bağlılığı", "Erken çıkışta kesinti"],
      },
      {
        name: "Banka Aracılığı",
        description: "Banka şubesi veya mobil uygulama üzerinden anlaşmalı emeklilik şirketi ile BES sözleşmesi.",
        minAmount: "Bankaya göre",
        liquidity: "Düşük",
        cost: "Yönetim gider kesintisi",
        tax: "Emeklilikte avantajlı",
        storage: "Elektronik",
        ease: "Çok Kolay",
        pros: ["Mevcut banka müşterisi avantajı", "Otomatik ödeme", "Tek uygulama"],
        cons: ["Sınırlı emeklilik şirketi seçeneği", "Fon çeşitliliği az olabilir"],
      },
    ],
  },
  {
    id: "altin",
    name: "Altın",
    shortDesc: "Fiziki veya hesap üzerinden altın yatırımı",
    category: "Emtia",
    risk: 3,
    liquidity: "Yüksek",
    minAmount: "Gram altın ile başlanabilir",
    returnType: "Fiyat artışı",
    tax: "Banka altınında stopaj; fizikide KDV",
    icon: "🥇",
    description: "Altın, Türkiye'de en yaygın yatırım araçlarından biridir. Fiziki altın (gram, çeyrek, cumhuriyet), banka altın hesabı, altın fonları veya borsada işlem gören altın sertifikaları ile yatırım yapılabilir. BIST'te işlem gören Darphane Altın Sertifikası (ALTIN.S1) %0 stopaj avantajı sunarken arzı sabit olduğu için spot altına göre %23-80 arası primle işlem görebilir. Bu prim makasının daralması (ek ihraç veya satış baskısı) sertifika fiyatında ani düşüş riski taşır. Fiziki altında işçiliksiz 24 ayar gram altın veya 22 ayar burma/bilezik tercih edilmeli; taşlı/işçilikli ürünlerde makas %30-40'a çıkabilir.",
    pros: ["Enflasyona karşı koruma", "Yüksek likidite", "Kolay erişim", "Kültürel güven", "BIST sertifikasında %0 stopaj avantajı"],
    cons: ["Getiri garantisi yok", "Fizikide saklama maliyeti", "Kısa vadede dalgalanma", "Getiri vermez (temettü/faiz yok)", "BIST sertifikası spot altına göre primli işlem görebilir"],
    suitableFor: "Enflasyondan korunmak isteyen, orta-uzun vadeli yatırımcılar",
    notSuitableFor: "Kısa vadede yüksek getiri bekleyenler, temettü/faiz geliri isteyenler",
    commonMistakes: ["Yüksek spread'li fiziki altın (taşlı/işçilikli takı) almak", "Sahte altın riskini göz ardı etmek", "Saklama güvenliğini önemsememek", "BIST sertifikasında spot altına göre oluşan primi kontrol etmemek, makas daralması riskini hesaba katmamak"],
    regulator: "BDDK / SPK",
    methods: [
      {
        name: "Fiziki Altın (Kuyumcu)",
        description: "Kuyumculardan gram altın, çeyrek altın, cumhuriyet altını veya bilezik alımı. En geleneksel yöntem.",
        minAmount: "1 gram altın",
        liquidity: "Yüksek",
        cost: "İşçilik + alış-satış spread (%3–8)",
        tax: "KDV (%20)",
        storage: "Ev/kasa — siz sorumlusunuz",
        ease: "Çok Kolay",
        pros: ["Anında fiziki sahiplik", "Her yerde alım-satım", "Kriz anında güven"],
        cons: ["Saklama riski", "Yüksek spread", "KDV maliyeti", "Sahtecilik riski"],
      },
      {
        name: "Banka Altın Hesabı",
        description: "Bankada gram bazlı altın hesabı açarak fiziksel altın olmadan altına yatırım. Alım-satım banka kurları üzerinden.",
        minAmount: "0,01 gram veya 1 gram (bankaya göre)",
        liquidity: "Yüksek",
        cost: "Spread (düşük işçilik)",
        tax: "Stopaj (%15)",
        storage: "Bankada — güvenli",
        ease: "Kolay",
        pros: ["Güvenli saklama", "Düşük spread", "7/24 işlem (bazı bankalar)", "Küçük tutarlarla başlangıç"],
        cons: ["Fiziki altın yok", "Banka spread'i", "Stopaj kesintisi"],
      },
      {
        name: "Altın Fonları",
        description: "Altına dayalı yatırım fonları veya BES altın fonları. TEFAS üzerinden alınabilir.",
        minAmount: "100–500 TL civarı",
        liquidity: "Yüksek (T+1–2)",
        cost: "Yönetim ücreti (yıllık ~%1)",
        tax: "Stopaj (fon türüne göre)",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Profesyonel yönetim", "Düşük giriş", "Otomatik çeşitlendirme", "Fiziki saklama yok"],
        cons: ["Yönetim ücreti", "Fon performans riski", "Doğrudan altın sahipliği değil"],
      },
      {
        name: "BIST Altın Sertifikası (ALTIN.S1)",
        description: "Borsa İstanbul'da işlem gören, Darphane garantili, her biri 0,01 gram altını temsil eden altın sertifikaları. Aracı kurum hesabı ile alınıp satılır. Fiziki altına dönüşüm hakkı vardır (en az 50 gram).",
        minAmount: "1 lot (~0,01 gram altın)",
        liquidity: "Yüksek (borsa saatleri)",
        cost: "Düşük komisyon (%0,1–0,3)",
        tax: "%0 stopaj (kazanç vergisiz)",
        storage: "Elektronik (MKK kaydı)",
        ease: "Orta",
        pros: ["%0 stopaj ile vergisiz kazanç", "Borsa likiditesi", "Çok düşük minimum (0,01 gr)", "Fiziki altına dönüşüm hakkı", "Şeffaf fiyat"],
        cons: ["Spot altına göre primli işlem görebilir (%23-80 arası makas)", "Arz sabit (5 ton), talep arttıkça fiyat kopar", "Arbitraj mekanizması yok, makas kapanmayabilir", "Ek ihraç veya büyük satışlarda makas daralırsa sert düşüş riski"],
      },
    ],
  },
  {
    id: "doviz",
    name: "Döviz",
    shortDesc: "USD, EUR ve diğer yabancı paralar",
    category: "Döviz",
    risk: 3,
    liquidity: "Çok Yüksek",
    minAmount: "Bankaya göre değişir",
    returnType: "Kur farkı + mevduat faizi",
    tax: "Stopaj (mevduat faizinde)",
    icon: "💵",
    description: "Döviz yatırımı, yabancı para birimlerine (ABD doları, avro vb.) sahip olmayı ifade eder. Hem kur artışından hem de döviz mevduat faizinden getiri elde edilebilir. 2026'da TCMB'nin dezenflasyon stratejisi kapsamında TL'de kontrollü reel değerlenme beklenmektedir. Dolar/TL için yıl sonu beklentileri 49-56 bandındadır. TL'nin reel değerlenmesi carry trade pozisyonlarını cazip kılmakta ancak döviz bazında yatırım düşünenler için kur artışının enflasyonun gerisinde kalması reel getiriyi sınırlayabilir.",
    pros: ["Kur koruması (TL değer kaybına karşı)", "Yüksek likidite", "Kolay erişim", "Döviz mevduat faizi"],
    cons: ["Kur dalgalanması", "TL reel değerlenme dönemlerinde getiri sınırlı", "Spread maliyeti", "Faiz düşük olabilir", "TCMB politikalarına bağlı"],
    suitableFor: "Döviz ihtiyacı olan veya kur riskinden korunmak isteyenler",
    notSuitableFor: "Uzun vadede TL bazlı yatırım düşünenler, faiz geliri bekleyenler",
    commonMistakes: ["Spread maliyetini hesaplamamak", "Fiziki dövizi güvensiz saklamak", "Tüm birikimi tek paraya yatırmak"],
    regulator: "TCMB / BDDK",
    methods: [
      {
        name: "Banka (Döviz Hesabı)",
        description: "Bankada döviz tevdiat hesabı açarak USD, EUR vb. alım. Vadeli veya vadesiz seçenekler.",
        minAmount: "1 USD/EUR (bankaya göre)",
        liquidity: "Çok Yüksek",
        cost: "Spread (alış-satış farkı)",
        tax: "Kur farkı vergisi yok; faizde stopaj",
        storage: "Bankada",
        ease: "Çok Kolay",
        pros: ["Güvenli", "Vadeli faiz seçeneği", "Kolay erişim", "Mobil işlem"],
        cons: ["Spread maliyeti", "Faiz düşük", "Kur riski devam eder"],
      },
      {
        name: "Döviz Bürosu",
        description: "Seyyar veya sabit döviz bürolarından nakit döviz alım-satımı. Genelde fiziki nakit.",
        minAmount: "Düşük",
        liquidity: "Yüksek (nakit)",
        cost: "Spread (bankadan yüksek olabilir)",
        tax: "Kur farkı vergisi yok",
        storage: "Nakit — siz sorumlusunuz",
        ease: "Kolay",
        pros: ["Anında nakit", "Pazarlık imkânı", "Esnek tutar"],
        cons: ["Güvenlik riski", "Yüksek spread", "Sahte para riski", "Kayıt dışı"],
      },
      {
        name: "Aracı Kurum (Döviz Fonu / ETF)",
        description: "Döviz cinsinden fon veya döviz endeksli yatırım araçları ile dolaylı döviz pozisyonu.",
        minAmount: "Fona göre",
        liquidity: "Yüksek",
        cost: "Komisyon + yönetim ücreti",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Profesyonel yönetim", "Çeşitlendirme", "Düşük minimum"],
        cons: ["Dolaylı exposure", "Yönetim ücreti", "Fon riski"],
      },
    ],
  },
  {
    id: "mevduat",
    name: "Mevduat / Faiz Hesabı",
    shortDesc: "Bankada vadeli veya vadesiz TL birikim",
    category: "Bankacılık",
    risk: 1,
    liquidity: "Yüksek",
    minAmount: "Bankaya göre (genelde düşük)",
    returnType: "Faiz geliri",
    tax: "Stopaj (%15–%17,5)",
    icon: "🏧",
    description: "Mevduat, paranızı bankaya belirli bir süre veya vadesiz olarak yatırarak faiz kazanmanızı sağlayan en güvenli yatırım araçlarından biridir. Tasarruf Mevduatı Sigorta Fonu (TMSF) kapsamında sigortalıdır. 2026'da politika faizinin %38'den %29-30'a gerilemesi beklense de mevduat faizleri halen pozitif reel faiz sunmaktadır (enflasyon ~%31, mevduat ~%48). Stopaj oranları vadeye göre %15-17,5 arasındadır. Net getiri hesaplanırken enflasyon ve stopaj birlikte değerlendirilmelidir.",
    pros: ["Düşük risk", "TMSF sigortası (200.000 TL'ye kadar)", "Öngörülebilir getiri", "Pozitif reel faiz imkânı (2026)", "Kolay erişim"],
    cons: ["Enflasyonun altında kalabilir (reel getiri riski)", "Getiri sınırlı", "Stopaj kesintisi (%15-17,5)", "Faiz değişkenliği"],
    suitableFor: "Risk almak istemeyen, kısa vadeli birikim sahipleri",
    notSuitableFor: "Enflasyon üzerinde getiri arayan, uzun vadeli büyüme hedefleyenler",
    commonMistakes: ["Vadeyi ihtiyaca göre ayarlamamak", "Erken bozma cezasını bilmemek", "Stopaj sonrası net getiriyi hesaplamamak"],
    regulator: "BDDK / TMSF",
    methods: [
      {
        name: "Vadeli TL Mevduat",
        description: "Belirli bir süre (1 ay – 1 yıl) para bankada kilitlenir, karşılığında faiz alınır. En yaygın mevduat türü.",
        minAmount: "Genelde 1.000 TL",
        liquidity: "Düşük (vade sonuna kadar)",
        cost: "Yok (faiz brüt/stopajlı)",
        tax: "Stopaj (%15–17,5)",
        storage: "Bankada",
        ease: "Çok Kolay",
        pros: ["Yüksek faiz (vadesize göre)", "TMSF sigortası", "Öngörülebilir getiri"],
        cons: ["Vade boyunca çekilemez", "Erken bozmada ceza", "Enflasyon riski"],
      },
      {
        name: "Vadesiz TL Hesap",
        description: "İstediğiniz zaman para çekebileceğiniz hesap. Faiz oranı düşük veya yok.",
        minAmount: "Düşük",
        liquidity: "Çok Yüksek",
        cost: "Yok",
        tax: "Faiz varsa stopaj",
        storage: "Bankada",
        ease: "Çok Kolay",
        pros: ["Anında erişim", "Esneklik", "TMSF sigortası"],
        cons: ["Çok düşük/getirisiz", "Enflasyonda erir"],
      },
      {
        name: "Katılma Hesabı (Faizsiz)",
        description: "Katılım bankalarında kâr-zarar ortaklığı prensibiyle çalışan faizsiz mevduat hesabı.",
        minAmount: "Bankaya göre",
        liquidity: "Vadeye göre değişir",
        cost: "Yok",
        tax: "Kâr payında stopaj",
        storage: "Bankada",
        ease: "Kolay",
        pros: ["Faizsiz yapı", "Dini hassasiyete uygun", "TMSF sigortası"],
        cons: ["Getiri garantisi yok", "Kâr payı değişken", "Seçenek sınırlı"],
      },
    ],
  },
  {
    id: "repo",
    name: "Repo",
    shortDesc: "Kısa vadeli devlet tahvili alım-satımı",
    category: "Para Piyasası",
    risk: 1,
    liquidity: "Çok Yüksek",
    minAmount: "Bankaya göre değişir",
    returnType: "Kısa vadeli faiz",
    tax: "Stopaj uygulanır",
    icon: "🔄",
    description: "Repo (Repurchase Agreement), kısa vadede devlet tahvillerinin geçici alım-satımıdır. Mevduata benzer düşük riskli bir araçtır, genellikle biraz daha yüksek getiri sunar.",
    pros: ["Düşük risk", "Kısa vade esnekliği", "Mevduattan yüksek getiri potansiyeli", "Kolay işlem"],
    cons: ["Getiri sınırlı", "Enflasyon riski", "Vade sonuna kadar beklemek gerekebilir", "Bireysel erişim sınırlı olabilir"],
    suitableFor: "Kısa vadeli nakit değerlendirmek isteyen, düşük risk profilli yatırımcılar",
    notSuitableFor: "Uzun vadeli yatırımcılar, yüksek getiri arayanlar",
    commonMistakes: ["Vade uyumunu gözetmemek", "Mevduat ile karşılaştırmamak", "Minimum tutar sınırını kontrol etmemek"],
    regulator: "TCMB / BDDK",
    methods: [
      {
        name: "Banka Repo",
        description: "Banka üzerinden 1–90 gün vadeli repo işlemi. Genelde internet bankacılığından yapılır.",
        minAmount: "Genelde 10.000 TL+",
        liquidity: "Yüksek (vade sonu)",
        cost: "Yok",
        tax: "Stopaj",
        storage: "Bankada",
        ease: "Kolay",
        pros: ["Güvenli", "Mevduattan yüksek getiri", "Kısa vade"],
        cons: ["Minimum tutar yüksek olabilir", "Vade boyunca erişim yok"],
      },
      {
        name: "Aracı Kurum Repo",
        description: "Aracı kurum platformu üzerinden repo ve ters repo işlemleri.",
        minAmount: "Kuruma göre",
        liquidity: "Yüksek",
        cost: "Komisyon (düşük)",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Esnek vade", "Rekabetçi oran", "Online işlem"],
        cons: ["Aracı kurum hesabı gerekir", "Minimum tutar"],
      },
    ],
  },
  {
    id: "gayrimenkul",
    name: "Gayrimenkul",
    shortDesc: "Konut, arsa veya ticari mülk yatırımı",
    category: "Gayrimenkul",
    risk: 3,
    liquidity: "Düşük",
    minAmount: "Yüksek (milyonlarca TL)",
    returnType: "Kira geliri + değer artışı",
    tax: "Gelir vergisi + emlak vergisi",
    icon: "🏠",
    description: "Gayrimenkul yatırımı, konut, arsa veya ticari mülk satın alarak kira geliri ve değer artışından faydalanmayı içerir. Kredili alımda sabit faizli konut kredisi kullanıldığında enflasyon avantajı devreye girer: nominal taksit sabit kalırken enflasyon ve gelir artışı sayesinde reel borç yükü zamanla erir; konut değeri artarken kredi bakiyesi nominal kaldığı için net servet büyür. Alternatif olarak Gayrimenkul Yatırım Ortaklıkları (GYO) borsada işlem görür.",
    pros: ["Kira geliri", "Sabit faizli kredide enflasyonun borcu eritmesi", "Somut varlık", "Enflasyona karşı uzun vadeli koruma", "GYO ile likidite seçeneği"],
    cons: ["Yüksek giriş maliyeti", "Düşük likidite", "Bakım ve yönetim maliyeti", "Piyasa döngüleri", "Kredi faizleri yüksekse giriş maliyeti artar"],
    suitableFor: "Uzun vadeli, yüksek sermayeli yatırımcılar",
    notSuitableFor: "Düşük sermayeli yatırımcılar, nakde hızlı erişim ihtiyacı olanlar",
    commonMistakes: ["Tapu araştırması yapmamak", "Konum analizini atlamak", "Bakım ve vergi maliyetlerini unutmak", "Kredi faiz türünü (sabit/değişken) doğru seçmemek", "Kira çarpanı hesabı yapmadan satın almak"],
    regulator: "Tapu Kadastro / SPK (GYO)",
    methods: [
      {
        name: "Konut Alımı (Kredili veya Peşin)",
        description: "Ev, daire veya villa satın alarak kira geliri veya değer artışı hedefleme. Kredi ile alımda enflasyon borçluyu avantajlı kılar: sabit faizli kredide nominal taksit aynı kalırken, enflasyon ve gelir artışı sayesinde reel borç yükü yıllar içinde erir. Konut değeri enflasyonla artarken (veya reel bazda korurken) borç nominal kaldığı için net servet hızla büyür.",
        minAmount: "Yüksek (milyonlarca TL)",
        liquidity: "Düşük (aylar–yıllar)",
        cost: "Tapu harcı + emlakçı + bakım + kredi faizi (varsa)",
        tax: "Kira gelir vergisi + emlak vergisi",
        storage: "Fiziki mülk",
        ease: "Orta",
        pros: ["Kira geliri", "Somut varlık", "Sabit faizli kredide enflasyonun borcu eritmesi avantajı", "Konut değeri artarken kredi bakiyesi nominal kalır, net servet büyür", "Yaşam alanı da olabilir"],
        cons: ["Yüksek sermaye", "Satış süresi uzun", "Bakım maliyeti", "Kiracı yönetimi", "Değişken faizli kredi riskli (enflasyon düşerken faiz yükü artabilir)"],
      },
      {
        name: "Arsa / Arazi",
        description: "İmarlı veya imarsız arsa alımı. Değer artışı odaklı, kira geliri genelde yok.",
        minAmount: "Bölgeye göre değişken",
        liquidity: "Çok Düşük",
        cost: "Tapu harcı + vergi",
        tax: "Değer artış kazancı vergisi (satışta)",
        storage: "Fiziki",
        ease: "Zor",
        pros: ["Yüksek değer artış potansiyeli", "Düşük bakım", "Imar beklentisi"],
        cons: ["Likidite çok düşük", "İmar riski", "Spekülatif", "Uzun vade şart"],
      },
      {
        name: "Ticari Gayrimenkul",
        description: "Dükkan, ofis, depo gibi ticari mülk alımı. Kira geliri genelde konuttan yüksek.",
        minAmount: "Çok yüksek",
        liquidity: "Düşük",
        cost: "Tapu + bakım + yönetim",
        tax: "Kira gelir vergisi + KDV (ticari)",
        storage: "Fiziki",
        ease: "Zor",
        pros: ["Yüksek kira getirisi", "Uzun vadeli sözleşmeler", "Profesyonel kiracılar"],
        cons: ["Çok yüksek sermaye", "Doluluk riski", "Ekonomiye duyarlı"],
      },
    ],
  },
  {
    id: "gyo",
    name: "GYO (Gayrimenkul Yatırım Ortaklığı)",
    shortDesc: "Borsada işlem gören gayrimenkul fonu",
    category: "Gayrimenkul",
    risk: 3,
    liquidity: "Orta",
    minAmount: "Hisse senedi gibi (tek lot)",
    returnType: "Temettü + fiyat artışı",
    tax: "Stopaj + beyan (koşullu)",
    icon: "🏢",
    description: "GYO'lar, portföylerinde gayrimenkul bulunduran ve borsada hisse senedi gibi işlem gören şirketlerdir. Doğrudan mülk almadan gayrimenkul yatırımı yapmayı sağlar. 2026'da faiz indirim döngüsü GYO sektörü için olumlu katalizördür: düşen faizler gayrimenkul talebini canlandırır ve GYO'ların finansman maliyetini azaltır. Kurumsal raporlarda bankacılıkla birlikte en beğenilen sektörler arasındadır.",
    pros: ["Düşük giriş tutarı", "Profesyonel yönetim", "Temettü potansiyeli", "Borsada likidite"],
    cons: ["Hisse volatilitesi", "Gayrimenkul piyasa riski", "Yönetim maliyeti", "Sektöre bağlılık"],
    suitableFor: "Gayrimenkule yatırım yapmak isteyen ama doğrudan mülk alamayanlar",
    notSuitableFor: "Doğrudan gayrimenkul sahibi olmak isteyenler",
    commonMistakes: ["GYO ile hisse senedini aynı görmek", "Portföy içeriğini araştırmamak", "Temettü garantisi olduğunu varsaymak"],
    regulator: "SPK / BIST",
    methods: [
      {
        name: "Aracı Kurum (BIST)",
        description: "Aracı kurum hesabı açarak BIST'te işlem gören GYO hisselerini alım-satım. Tek ve ana yöntem.",
        minAmount: "1 lot (GYO'ya göre değişir)",
        liquidity: "Orta (borsa saatleri)",
        cost: "Komisyon",
        tax: "Temettü stopajı; satışta koşullu muafiyet",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Düşük giriş tutarı", "Borsa likiditesi", "Temettü geliri", "Profesyonel portföy yönetimi"],
        cons: ["Hisse fiyat volatilitesi", "Borsa bilgisi gerekir", "Sektör riski"],
      },
    ],
  },
  {
    id: "kripto",
    name: "Kripto Para",
    shortDesc: "Bitcoin, Ethereum ve diğer dijital varlıklar",
    category: "Dijital Varlık",
    risk: 5,
    liquidity: "Yüksek",
    minAmount: "Platforma göre çok düşük",
    returnType: "Fiyat artışı (spekülatif)",
    tax: "Gelir vergisi beyanı gerekebilir",
    icon: "₿",
    description: "Kripto paralar, blockchain teknolojisi üzerinde çalışan dijital varlıklardır. Türkiye'de SPK düzenlemesi altında lisanslı platformlar aracılığıyla alınıp satılabilir. Bitcoin ve Ethereum başta olmak üzere binlerce kripto para mevcuttur. 2025 itibarıyla SPK'dan lisans alan platformlar yasal zeminde faaliyet göstermektedir. Kripto kazançları gelir vergisine tabidir ve beyan edilmelidir. Soğuk cüzdan (cold wallet) kullanımı güvenlik için önerilir. Yatırımın tamamını kaybetme riski vardır, bu nedenle portföyün sadece küçük bir kısmı (<%5-10) kripto paralara ayrılmalıdır.",
    pros: ["Yüksek getiri potansiyeli", "7/24 işlem", "Düşük giriş tutarı", "Küresel erişim", "Blockchain teknolojisine yatırım"],
    cons: ["Aşırı volatilite", "Regülasyon belirsizliği", "Güvenlik riski (hack, dolandırıcılık)", "Kayıp riski yüksek (tüm sermaye kaybedilebilir)", "Vergi beyan yükümlülüğü"],
    suitableFor: "Çok yüksek risk toleranslı, spekülatif yatırımcılar",
    notSuitableFor: "Düşük risk toleranslı, ana sermayesini riske atamayacak yatırımcılar",
    commonMistakes: ["Tüm sermayeyi kriptoya yatırmak", "Güvenilir platform seçmemek", "Özel anahtarları kaybetmek", "Vergi yükümlülüğünü ihmal etmek"],
    regulator: "SPK / MASAK",
    methods: [
      {
        name: "SPK Lisanslı Platform",
        description: "Türkiye'de SPK'dan lisans almış kripto varlık alım-satım platformları. Yasal ve denetimli kanal.",
        minAmount: "Çok düşük (10 TL bile olabilir)",
        liquidity: "Yüksek (7/24)",
        cost: "İşlem komisyonu (%0,1–1)",
        tax: "Gelir vergisi beyanı",
        storage: "Platform cüzdanı",
        ease: "Kolay",
        pros: ["Yasal güvence", "TL ile alım", "Kolay arayüz", "7/24 işlem"],
        cons: ["Platform hack riski", "Aşırı volatilite", "Vergi belirsizliği"],
      },
      {
        name: "Soğuk Cüzdan (Cold Wallet)",
        description: "Kriptoyu offline donanım cüzdanında saklama. Platformdan alıp kendi cüzdanınıza transfer.",
        minAmount: "Platform minimumuna bağlı",
        liquidity: "Orta (transfer süresi)",
        cost: "Donanım cüzdan maliyeti + transfer ücreti",
        tax: "Gelir vergisi beyanı",
        storage: "Fiziki cihaz — siz sorumlusunuz",
        ease: "Zor",
        pros: ["En güvenli saklama", "Hack'e karşı koruma", "Tam kontrol"],
        cons: ["Cihaz kaybı = coin kaybı", "Teknik bilgi gerekir", "Satış için transfer gerekir"],
      },
    ],
  },
  {
    id: "viop",
    name: "VİOP (Vadeli İşlemler)",
    shortDesc: "Endeks, döviz ve emtia vadeli kontratları",
    category: "Türev",
    risk: 5,
    liquidity: "Yüksek",
    minAmount: "Teminat gereksinimine bağlı",
    returnType: "Fiyat farkından kâr/zarar",
    tax: "Stopaj uygulanır",
    icon: "📉",
    description: "Vadeli İşlem ve Opsiyon Piyasası (VİOP), endeks, döviz, emtia gibi varlıkların gelecekteki fiyatlarına yönelik kontratların işlem gördüğü piyasadır. Kaldıraçlı işlem yapılabilir: küçük bir teminatla büyük pozisyon açılır, bu kârı da zararı da oransal olarak büyütür. Zarar durumunda teminat tamamlama çağrısı (margin call) gelir, eklenmezse pozisyon zorla kapatılır. Stop-loss kullanımı hayati önemdedir. BIST 30 ve USD/TRY en likit kontratlardır.",
    pros: ["Kaldıraç ile yüksek getiri potansiyeli", "Hedge (koruma) imkânı", "Çeşitli enstrüman", "Likidite"],
    cons: ["Çok yüksek risk", "Kaldıraç kaybı büyütür", "İleri seviye bilgi gerekir", "Tüm sermaye kaybedilebilir"],
    suitableFor: "Deneyimli, profesyonel yatırımcılar ve kurumsal oyuncular",
    notSuitableFor: "Yeni başlayanlar, düşük risk profilli yatırımcılar",
    commonMistakes: ["Kaldıraç etkisini tam anlamamak", "Teminat tamamlama çağrılarını ciddiye almamak", "Stop-loss kullanmamak"],
    regulator: "BIST / SPK",
    methods: [
      {
        name: "Endeks Vadeli (BIST30/S100)",
        description: "BIST 30 veya BIST 100 endeksine dayalı vadeli kontratlar. Endeks yönüne bahis.",
        minAmount: "Teminat (~birkaç bin TL)",
        liquidity: "Çok Yüksek",
        cost: "Komisyon + spread",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Zor",
        pros: ["Yüksek likidite", "Kaldıraç", "Hedge imkânı"],
        cons: ["Kaldıraçlı kayıp riski", "Vade sonu zorunluluğu", "İleri bilgi şart"],
      },
      {
        name: "Döviz Vadeli (USD/TRY)",
        description: "Dolar/TL kuruna dayalı vadeli kontratlar. Kur hareketlerinden kâr/zarar.",
        minAmount: "Teminat gereksinimine bağlı",
        liquidity: "Yüksek",
        cost: "Komisyon",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Zor",
        pros: ["Kur hedge", "Kaldıraç", "7/24 değil ama geniş saat"],
        cons: ["Aşırı volatilite", "Teminat tamamlama riski"],
      },
      {
        name: "Emtia Vadeli (Altın/Gümüş)",
        description: "Altın ve gümüş fiyatına dayalı vadeli kontratlar.",
        minAmount: "Teminat gereksinimine bağlı",
        liquidity: "Orta",
        cost: "Komisyon",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Zor",
        pros: ["Fiziki altın olmadan emtia exposure", "Kaldıraç"],
        cons: ["Yüksek risk", "Vade yönetimi", "Teminat riski"],
      },
    ],
  },
  {
    id: "sukuk",
    name: "Sukuk (Katılım Finans)",
    shortDesc: "Faizsiz tahvil benzeri İslami finans aracı",
    category: "Katılım Finans",
    risk: 2,
    liquidity: "Orta",
    minAmount: "İhraç türüne göre değişir",
    returnType: "Kâr payı (faiz değil)",
    tax: "Stopaj uygulanır",
    icon: "☪️",
    description: "Sukuk, faiz yerine varlık tabanlı kâr payı dağıtan İslami finans enstrümanıdır. Devlet sukuku ve özel sektör sukukları mevcuttur. Faizsiz bankacılık prensiplerine uygun yatırım arayanlar için uygundur.",
    pros: ["Faizsiz yapı", "Varlık destekli", "Devlet sukuku güvenli", "Etik yatırım"],
    cons: ["Sınırlı seçenek", "Likidite kısıtlı olabilir", "Getiri sınırlı", "Yapı karmaşık olabilir"],
    suitableFor: "Faizsiz yatırım arayan, İslami finans prensiplerine uygun yatırımcılar",
    notSuitableFor: "Yüksek getiri arayan, konvansiyonel tahvillere alışkın yatırımcılar",
    commonMistakes: ["Sukuk yapısını anlamadan almak", "Likidite riskini ihmal etmek", "Getiriyi tahvil ile aynı görmek"],
    regulator: "BDDK / SPK",
    methods: [
      {
        name: "Katılım Bankası",
        description: "Katılım bankalarının şubesi veya mobil uygulaması üzerinden sukuk alımı.",
        minAmount: "Bankaya göre",
        liquidity: "Orta",
        cost: "Spread (düşük)",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Faizsiz yapı", "Güvenilir", "Devlet sukuku erişimi"],
        cons: ["Sınırlı ürün", "Getiri değişken"],
      },
      {
        name: "Katılım Finans Kuruluşu",
        description: "Katılım esaslı finansman şirketleri aracılığıyla özel sektör sukuku alımı.",
        minAmount: "İhraç türüne göre",
        liquidity: "Düşük–Orta",
        cost: "Yönetim + spread",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Özel sektör sukuku", "Çeşitlendirme", "Etik yatırım"],
        cons: ["Az bilinen kuruluşlar", "Likidite riski"],
      },
    ],
  },
  {
    id: "gumus-emtia",
    name: "Gümüş & Emtia",
    shortDesc: "Gümüş, platin ve diğer değerli madenler",
    category: "Emtia",
    risk: 4,
    liquidity: "Orta",
    minAmount: "Gram bazında değişir",
    returnType: "Fiyat artışı",
    tax: "KDV ve stopaj uygulanabilir",
    icon: "⚙️",
    description: "Gümüş, platin ve diğer emtialar altına alternatif veya tamamlayıcı yatırım araçlarıdır. Endüstriyel talep (güneş panelleri, elektronik, otomotiv) ve yatırım talebi fiyatı etkiler. Gümüş, altına göre daha volatildir ancak sanayi kullanımı nedeniyle büyüme dönemlerinde altından daha iyi performans gösterebilir. 2026'da küresel talep yavaşlaması emtia fiyatlarını baskılasa da yeşil enerji dönüşümü gümüş ve bazı kritik emtialar için uzun vadeli talep yaratmaktadır. Fiziki gümüşte oksitlenme ve saklama maliyeti göz ardı edilmemelidir.",
    pros: ["Altından ucuz giriş", "Endüstriyel talep", "Enflasyona karşı koruma", "Çeşitlendirme"],
    cons: ["Altından daha volatil", "Saklama maliyeti", "Niş piyasa", "Getiri garantisi yok"],
    suitableFor: "Emtia yatırımına ilgi duyan, orta-yüksek risk profilli yatırımcılar",
    notSuitableFor: "Kısa vadeli istikrarlı getiri arayanlar",
    commonMistakes: ["Saklama maliyetlerini hesaba katmamak", "Endüstriyel talebi takip etmemek", "Altına göre daha volatil olduğunu unutmamak"],
    regulator: "BDDK / SPK",
    methods: [
      {
        name: "Fiziki Gümüş (Kuyumcu)",
        description: "Kuyumculardan gram gümüş, gümüş külçe veya sikke alımı.",
        minAmount: "1 gram gümüş",
        liquidity: "Orta",
        cost: "Spread + işçilik",
        tax: "KDV",
        storage: "Ev/kasa — siz sorumlusunuz",
        ease: "Kolay",
        pros: ["Somut varlık", "Altından ucuz", "Kolay erişim"],
        cons: ["Saklama riski", "Oksitlenme", "Spread yüksek"],
      },
      {
        name: "Banka Emtia Hesabı",
        description: "Bazı bankaların sunduğu gram bazlı gümüş veya emtia hesabı.",
        minAmount: "Bankaya göre",
        liquidity: "Yüksek",
        cost: "Spread",
        tax: "Stopaj",
        storage: "Bankada",
        ease: "Kolay",
        pros: ["Güvenli saklama", "Kolay alım-satım", "Düşük minimum"],
        cons: ["Her bankada yok", "Sınırlı emtia seçeneği"],
      },
      {
        name: "Emtia Fonu",
        description: "Gümüş veya emtia sepetine yatırım yapan yatırım fonları. TEFAS üzerinden.",
        minAmount: "100–500 TL",
        liquidity: "Yüksek (T+1–2)",
        cost: "Yönetim ücreti",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Profesyonel yönetim", "Düşük giriş", "Çeşitlendirme"],
        cons: ["Yönetim ücreti", "Dolaylı sahiplik", "Sınırlı fon seçeneği"],
      },
    ],
    },
  {
    id: "kira-sertifikasi",
    name: "Kira Sertifikası",
    shortDesc: "Devletin ihraç ettiği faizsiz borçlanma aracı",
    category: "Katılım Finans",
    risk: 2,
    liquidity: "Orta",
    minAmount: "İhraç türüne göre",
    returnType: "Dönemsel kâr payı",
    tax: "Stopaj uygulanır",
    icon: "📜",
    description: "Kira sertifikası, Hazine ve Maliye Bakanlığı tarafından ihraç edilen, varlık kiralama şirketi aracılığıyla yatırımcıya dönemsel kâr payı ödemesi yapan faizsiz bir borçlanma aracıdır. Sukuk ile benzer ancak doğrudan devlet tarafından ihraç edilmesi ve daha düşük risk profili ile ayrışır.",
    pros: ["Devlet garantili", "Faizsiz yapı", "Düzenli kâr payı", "Düşük risk"],
    cons: ["Sınırlı ihraç dönemleri", "İkincil piyasa likiditesi düşük", "Getiri sınırlı", "Vade sonuna kadar beklemek gerekebilir"],
    suitableFor: "Faizsiz yatırım arayan, düşük risk profilli yatırımcılar",
    notSuitableFor: "Yüksek getiri arayan, kısa vadeli spekülatif yatırımcılar",
    commonMistakes: ["İhraç takvimini kaçırmak", "Vadeyi ihtiyaca göre seçmemek", "Sukuk ile aynı görüp farkları atlamak"],
    regulator: "Hazine ve Maliye",
    methods: [
      {
        name: "Katılım Bankası",
        description: "Katılım bankaları üzerinden kira sertifikası alımı. Banka şubesi veya mobil uygulama ile yapılabilir.",
        minAmount: "Bankaya göre",
        liquidity: "Orta",
        cost: "Spread (düşük)",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Faizsiz yapı", "Devlet güvencesi", "Kolay erişim"],
        cons: ["Sınırlı ürün", "Vadeye bağlılık"],
      },
      {
        name: "Hazine Doğrudan Satış",
        description: "Hazine ve Maliye Bakanlığı'nın belirli dönemlerde açtığı doğrudan satış kanalları ile kira sertifikası alımı.",
        minAmount: "İhraç tutarına göre",
        liquidity: "Düşük",
        cost: "Komisyonsuz",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Aracısız alım", "Düşük maliyet", "Doğrudan devlet"],
        cons: ["Sadece ihraç dönemlerinde", "Erken satış zor"],
      },
    ],
  },
  {
    id: "para-piyasasi-fonu",
    name: "Para Piyasası Fonu",
    shortDesc: "Kısa vadeli likit araçlara yatırım yapan fon",
    category: "Fon",
    risk: 1,
    liquidity: "Çok Yüksek",
    minAmount: "100 TL ve üzeri",
    returnType: "Kısa vadeli faiz/kâr payı",
    tax: "Stopaj (%15)",
    icon: "💧",
    description: "Para piyasası fonları (PPF), vadeleri 90 günden kısa likit borçlanma araçlarına yatırım yapan, mevduata alternatif düşük riskli fonlardır. Genellikle vadeli mevduata yakın veya üzerinde getiri sağlar, istendiğinde T+0 veya T+1'de nakde çevrilebilir. 2026'da dezenflasyon süreciyle PPF getirilerinin %40 nominal / %13 reel seviyesine gerilemesi beklenmektedir ancak halen pozitif reel getiri sunmaya devam etmektedir. Stopaj oranı %15 olup mevduatla benzerdir.",
    pros: ["Mevduattan yüksek getiri potansiyeli", "Anında nakde çevrilebilir", "Çok düşük risk", "Stopaj avantajı"],
    cons: ["Getiri sınırlı", "Enflasyon altında kalabilir", "Fon yönetim ücreti", "Garanti getiri yok"],
    suitableFor: "Kısa vadeli nakitini değerlendirmek isteyen, düşük riskli yatırımcılar",
    notSuitableFor: "Uzun vadeli büyüme hedefleyen yatırımcılar",
    commonMistakes: ["Fon getirisini mevduatla karşılaştırmamak", "Anında çekilebileceğini sanmak", "Yönetim ücretini hesaba katmamak"],
    regulator: "SPK / TEFAS",
    methods: [
      {
        name: "Banka",
        description: "Banka şubesi veya internet bankacılığı üzerinden para piyasası fonu alımı.",
        minAmount: "100–500 TL",
        liquidity: "Çok Yüksek (T+0)",
        cost: "Yönetim ücreti (yıllık %0,5–1,5)",
        tax: "Stopaj (%15)",
        storage: "Elektronik",
        ease: "Çok Kolay",
        pros: ["Tanıdık kanal", "Anında bozma", "Düşük risk"],
        cons: ["Sınırlı fon seçeneği", "Yönetim ücreti"],
      },
      {
        name: "Aracı Kurum",
        description: "Aracı kurum platformu üzerinden geniş PPF yelpazesine erişim.",
        minAmount: "Fona göre",
        liquidity: "Çok Yüksek",
        cost: "Yönetim ücreti",
        tax: "Stopaj",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Geniş fon seçeneği", "Karşılaştırma kolay", "Düşük minimum"],
        cons: ["Aracı kurum hesabı gerekir", "Fon seçimi bilgisi gerekir"],
      },
    ],
  },
  {
    id: "birikim-hayat-sigortasi",
    name: "Birikim Hayat Sigortası",
    shortDesc: "Hayat sigortası ile birikimi birleştiren uzun vadeli ürün",
    category: "Bankacılık",
    risk: 2,
    liquidity: "Düşük",
    minAmount: "Aylık prim (düşük)",
    returnType: "Fon getirisi + hayat teminatı",
    tax: "Vergi avantajlı",
    icon: "🛡️",
    description: "Birikim Hayat Sigortası, hayat sigortası teminatı ile yatırım birikimini birleştiren uzun vadeli bir üründür. Ödenen primlerin bir kısmı hayat teminatına, bir kısmı yatırım fonlarına yönlendirilir. Vade sonunda birikim toplu olarak alınabilir.",
    pros: ["Hayat sigortası teminatı", "Vergi avantajı", "Disiplinli birikim", "Fon seçeneği"],
    cons: ["Uzun vade bağlılığı", "Erken çıkışta yüksek kesinti", "Düşük getiri potansiyeli", "Karmaşık ücret yapısı"],
    suitableFor: "Hayat sigortası ihtiyacı olan, uzun vadeli birikim yapmak isteyenler",
    notSuitableFor: "Kısa vadeli yatırımcılar, sadece yatırım odaklı olanlar",
    commonMistakes: ["Prim kesintilerini anlamamak", "Erken çıkış maliyetlerini bilmemek", "Sadece vergi avantajına odaklanmak"],
    regulator: "SEDDK / Sigortacılık Denetleme",
    methods: [
      {
        name: "Banka",
        description: "Banka şubesi veya mobil uygulama üzerinden anlaşmalı sigorta şirketi ile birikim hayat sigortası yaptırma.",
        minAmount: "Bankaya göre (aylık 500 TL+)",
        liquidity: "Düşük",
        cost: "Prim kesintisi + yönetim ücreti",
        tax: "Vergi avantajlı",
        storage: "Elektronik",
        ease: "Kolay",
        pros: ["Mevcut banka müşterisi avantajı", "Otomatik ödeme", "Tek uygulama"],
        cons: ["Sınırlı sigorta şirketi", "Fon seçeneği az olabilir"],
      },
      {
        name: "Sigorta Şirketi (Doğrudan)",
        description: "Doğrudan bir sigorta şirketinin web sitesi veya acentesi aracılığıyla poliçe açma.",
        minAmount: "Aylık 300–500 TL",
        liquidity: "Düşük",
        cost: "Prim kesintisi + fon işletim ücreti",
        tax: "Vergi avantajlı",
        storage: "Elektronik",
        ease: "Orta",
        pros: ["Geniş fon seçeneği", "Uzman danışmanlık", "Esnek prim"],
        cons: ["Acenta görüşmesi gerekir", "Uzun vade taahhüdü"],
      },
    ],
  },
];

const GLOSSARY = [
  { term: "BIST", definition: "Borsa İstanbul. Türkiye'nin tek borsası." },
  { term: "SPK", definition: "Sermaye Piyasası Kurulu. Sermaye piyasası düzenleyici kurumudur." },
  { term: "TEFAS", definition: "Türkiye Elektronik Fon Alım Satım Platformu. Tüm fonların tek yerden karşılaştırılıp alınabildiği platform." },
  { term: "DİBS", definition: "Devlet İç Borçlanma Senetleri (tahvil/bono). Devletin borçlanmak için ihraç ettiği menkul kıymetlerdir." },
  { term: "Stopaj", definition: "Kaynakta kesilen vergi. Yatırım getirisinden banka veya aracı kurum tarafından otomatik kesilir." },
  { term: "Temettü", definition: "Şirketlerin kârlarından hissedarlara dağıttığı kâr payı." },
  { term: "Likidite", definition: "Bir varlığın nakde çevrilme hızı ve kolaylığı. Yüksek likidite = hızlı nakde çevrilebilir." },
  { term: "Volatilite", definition: "Fiyat dalgalanmasının derecesi. Yüksek volatilite = fiyatın sık ve sert değişmesi." },
  { term: "Portföy", definition: "Yatırımcının sahip olduğu tüm varlıkların (hisse, tahvil, altın vb.) bütünü." },
  { term: "GYO", definition: "Gayrimenkul Yatırım Ortaklığı. Portföyünde gayrimenkul bulunduran ve borsada işlem gören şirket." },
  { term: "VİOP", definition: "Vadeli İşlem ve Opsiyon Piyasası. Gelecekteki fiyatlara yönelik kaldıraçlı kontratların işlem gördüğü piyasa." },
  { term: "BES", definition: "Bireysel Emeklilik Sistemi. Devlet katkılı, uzun vadeli emeklilik birikim sistemi." },
  { term: "TMSF", definition: "Tasarruf Mevduatı Sigorta Fonu. Mevduat hesaplarını belirli bir limite kadar sigortalar." },
  { term: "Repo", definition: "Repurchase Agreement. Kısa vadeli tahvil alım-satımına dayalı borçlanma aracı." },
  { term: "Sukuk", definition: "Faizsiz, varlık destekli İslami finans enstrümanı. Kâr payı esasına dayanır." },
  { term: "Endeks", definition: "Birden fazla hissenin veya varlığın ortak performansını ölçen gösterge. BIST 100, S&P 500 gibi." },
  { term: "Baz Puan (bps)", definition: "Faiz veya getiri oranlarındaki değişimi ifade eden birim. 1 baz puan = %0,01." },
  { term: "Spread", definition: "Alış ve satış fiyatı arasındaki fark. Düşük spread = düşük maliyet." },
  { term: "Arbitraj", definition: "Aynı varlığın farklı piyasalardaki fiyat farkından yararlanarak risksiz kâr elde etme." },
  { term: "Hedge", definition: "Portföyü fiyat dalgalanmalarına karşı koruma amaçlı işlem. Riskten korunma stratejisi." },
  { term: "ETF", definition: "Exchange Traded Fund. Borsada hisse senedi gibi işlem gören fon. Endeks, emtia veya sektör bazlı olabilir." },
  { term: "AOFM", definition: "Ağırlıklı Ortalama Fon Maliyeti. Fon alımlarında ortalama maliyeti hesaplamak için kullanılır." },
  { term: "MKK", definition: "Merkezi Kayıt Kuruluşu. Sermaye piyasası araçlarının kaydını elektronik ortamda tutar." },
  { term: "Takasbank", definition: "İstanbul Takas ve Saklama Bankası. Borsa işlemlerinin takasını ve saklamasını yapar." },
  { term: "Kaldıraç", definition: "Küçük bir teminatla daha büyük pozisyon açmayı sağlayan mekanizma. Kârı da zararı da büyütür." },
  { term: "Teminat Tamamlama", definition: "VİOP veya kaldıraçlı işlemlerde zarar durumunda ek teminat yatırma çağrısı (margin call)." },
  { term: "Bedelli Sermaye Artırımı", definition: "Şirketin yeni hisse senedi ihraç ederek mevcut hissedarlardan ek kaynak toplaması." },
  { term: "Bedelsiz Sermaye Artırımı", definition: "Şirketin iç kaynaklarını kullanarak hissedarlara ücretsiz yeni hisse dağıtması." },
  { term: "Rüçhan Hakkı", definition: "Mevcut hissedarın bedelli sermaye artırımında yeni hisseleri öncelikli alma hakkı." },
  { term: "Forward", definition: "Tezgah üstü piyasada (OTC) yapılan, gelecekteki bir tarihte belirli fiyattan alım-satım sözleşmesi." },
  { term: "Swap", definition: "İki tarafın belirli bir vadede nakit akışlarını veya varlıkları değiş tokuş ettiği türev sözleşme." },
  { term: "Opsiyon", definition: "Belirli bir varlığı gelecekte belirli fiyattan alma (call) veya satma (put) hakkı veren türev araç." },
  { term: "Likit Fon", definition: "Kısa vadeli borçlanma araçlarına yatırım yapan, istendiğinde nakde çevrilebilen düşük riskli para piyasası fonu." },
  { term: "PPF", definition: "Para Piyasası Fonu. Vadeleri 90 günden kısa araçlara yatırım yapan, mevduata alternatif düşük riskli fon." },
  { term: "F/K Oranı", definition: "Fiyat / Kazanç oranı. Bir hissenin fiyatının hisse başı kâra bölünmesiyle hesaplanır." },
  { term: "PD/DD", definition: "Piyasa Değeri / Defter Değeri oranı. Şirketin piyasa değerinin öz sermayesine oranı." },
  { term: "Temettü Verimi", definition: "Hisse başına ödenen yıllık temettünün hisse fiyatına oranı. Yatırımın ne kadar nakit getirdiğini gösterir." },
  { term: "Aktif Getiri", definition: "Bir portföyün veya fonun belirli bir endekse göre daha iyi (veya kötü) performans göstermesi." },
  { term: "Pasif Getiri", definition: "Bir endeksi birebir takip eden fon veya portföyün getirisi. Aktif yönetim gerektirmez." },
  { term: "Endeks Fonu", definition: "Belirli bir endeksi (ör. BIST 100) birebir takip eden pasif yönetimli fon." },
  { term: "Saklama Hizmeti", definition: "Yatırımcıya ait menkul kıymetlerin elektronik ortamda güvenle saklanması hizmeti." },
  { term: "Aracı Kurum", definition: "SPK lisanslı, borsada hisse senedi, tahvil ve diğer menkul kıymetlerin alım-satımına aracılık eden kurum." },
  { term: "Diversifikasyon", definition: "Risk dağıtmak için yatırımları farklı varlık türlerine, sektörlere veya bölgelere yayma." },
  { term: "Ortalama Maliyet (DCA)", definition: "Belirli aralıklarla düzenli alım yaparak ortalama maliyeti dengeleme stratejisi." },
  { term: "Değer Yatırımı", definition: "Piyasada düşük değerlenmiş, gerçek değerinin altında işlem gören hisseleri bulmaya odaklı strateji." },
  { term: "Büyüme Yatırımı", definition: "Kârını ve gelirini ortalamanın üzerinde artıran şirketlerin hisselerine yatırım yapma stratejisi." },
  { term: "Teknik Analiz", definition: "Geçmiş fiyat hareketleri ve hacim verilerine dayanarak gelecekteki fiyat yönünü tahmin etme yöntemi." },
  { term: "Temel Analiz", definition: "Şirketin finansal tabloları, sektörü ve makroekonomik verileri inceleyerek değerleme yapma yöntemi." },
  { term: "Stop-Loss", definition: "Belirlenen bir fiyat seviyesinde zararı durdurmak için otomatik satış emri." },
  { term: "Take-Profit", definition: "Belirlenen bir kâr seviyesinde pozisyonu otomatik kapatma emri." },
  { term: "Uzun Pozisyon (Long)", definition: "Bir varlığı fiyatı yükselecek beklentisiyle satın alma. Fiyat yükselince kâr, düşünce zarar." },
  { term: "Kısa Pozisyon (Short)", definition: "Bir varlığı fiyatı düşecek beklentisiyle ödünç alıp satma. Fiyat düşünce kâr, yükselince zarar." },
];

const TAX_INFO = [
  { instrument: "Hisse Senedi", withholding: "Stopaj yok (temettüde %15)", declaration: "Yıllık beyan gerekebilir", note: "1 yıldan uzun tutulan hisse satışında vergi muafiyeti. Kısa vadeli alım-satım kazancı beyan edilir." },
  { instrument: "Devlet Tahvili", withholding: "%0–%10 (vadeye göre)", declaration: "Genelde stopaj yeterli", note: "Vade uzadıkça stopaj oranı düşer. 5 yıl+ tahvillerde stopaj %0." },
  { instrument: "Mevduat Faizi", withholding: "%15–%17,5", declaration: "Stopaj yeterli", note: "6 aya kadar %17,5; 6 ay–1 yıl %15; 1 yıl+ %15." },
  { instrument: "Altın (Banka)", withholding: "%15", declaration: "Stopaj yeterli", note: "Fiziki altın alımında %20 KDV uygulanır. Hesap altınında KDV yok." },
  { instrument: "Yatırım Fonu", withholding: "%10–%17,5", declaration: "Stopaj yeterli", note: "Hisse fonu %10, tahvil fonu %15, para piyasası fonu %15." },
  { instrument: "Döviz Mevduat", withholding: "%15–%17,5", declaration: "Stopaj yeterli", note: "Kur farkı geliri vergilendirilmez. Sadece faiz geliri stopaja tabi." },
  { instrument: "Kripto Para", withholding: "Stopaj yok", declaration: "Gelir vergisi beyanı", note: "2025 itibarıyla SPK düzenlemesi altında. Alım-satım kazancı gelir vergisine tabi." },
  { instrument: "Eurobond", withholding: "%10–%15", declaration: "Stopaj yeterli (bazı durumlarda beyan)", note: "Yurt dışı tahvil faizinde stopaj oranı değişkendir." },
  { instrument: "BES", withholding: "Stopaj yok (emeklilikte)", declaration: "Emeklilikte stopaj kesilir", note: "Sistemden erken çıkışta %15–%25 stopaj kesintisi." },
  { instrument: "Gayrimenkul", withholding: "Stopaj yok", declaration: "Kira gelir vergisi + satışta değer artış", note: "Kira geliri için istisna tutarı (2026: ~33.000 TL) aşan kısım beyan edilir." },
  { instrument: "Kira Sertifikası", withholding: "%10 (vadeye göre)", declaration: "Stopaj yeterli", note: "Devlet kira sertifikalarında vadeye göre stopaj oranı değişir." },
  { instrument: "Para Piyasası Fonu", withholding: "%15", declaration: "Stopaj yeterli", note: "Likit fonlar da aynı stopaj oranına tabidir." },
];

const PORTFOLIO_EXAMPLES = [
  {
    profile: "Muhafazakar",
    risk: 1,
    desc: "Sermaye koruması önceliklidir. Düşük riskli, enflasyonun üzerinde getiri hedefler. Emekliliği yaklaşan veya risk almak istemeyen yatırımcılar için uygundur.",
    allocation: [
      { asset: "Mevduat / Repo", pct: 40 },
      { asset: "Para Piyasası Fonu", pct: 15 },
      { asset: "Devlet Tahvili / Kira Sertifikası", pct: 20 },
      { asset: "Altın (Banka Hesabı)", pct: 15 },
      { asset: "Yatırım Fonu (Tahvil Ağırlıklı)", pct: 10 },
    ],
    expectedReturn: "Yıllık %8–14 (enflasyon + küçük reel getiri)",
    suitableFor: "Emekliler, birikimini korumak isteyenler, kısa-orta vadeli hedefi olanlar",
  },
  {
    profile: "Dengeli",
    risk: 3,
    desc: "Büyüme ve koruma arasında denge kurar. Hem sabit getirili hem de büyüme odaklı varlıklara yatırım yapar. Orta vadede istikrarlı getiri hedefler.",
    allocation: [
      { asset: "Hisse Senedi (BIST)", pct: 25 },
      { asset: "Yatırım Fonu (Karma)", pct: 20 },
      { asset: "Altın / Emtia", pct: 15 },
      { asset: "Devlet Tahvili / Eurobond", pct: 15 },
      { asset: "BES", pct: 10 },
      { asset: "Döviz (USD/EUR sepeti)", pct: 10 },
      { asset: "Mevduat / PPF", pct: 5 },
    ],
    expectedReturn: "Yıllık %15–25 (enflasyon + reel büyüme)",
    suitableFor: "Orta vadeli (3–7 yıl) hedefi olan, risk almaya açık ama kontrollü yatırımcılar",
  },
  {
    profile: "Agresif",
    risk: 5,
    desc: "Yüksek büyüme odaklıdır. Portföyün büyük kısmı hisse senedi ve alternatif varlıklardan oluşur. Kısa vadede dalgalanma yüksektir ancak uzun vadede yüksek getiri hedeflenir.",
    allocation: [
      { asset: "Hisse Senedi (BIST + Yabancı)", pct: 40 },
      { asset: "Kripto Para", pct: 10 },
      { asset: "VİOP / Türev Ürünler", pct: 5 },
      { asset: "GYO", pct: 10 },
      { asset: "Gümüş / Emtia", pct: 10 },
      { asset: "Yatırım Fonu (Hisse Ağırlıklı)", pct: 15 },
      { asset: "Döviz", pct: 5 },
      { asset: "Altın", pct: 5 },
    ],
    expectedReturn: "Yıllık %25–50+ (yüksek volatilite)",
    suitableFor: "Uzun vadeli (7+ yıl) düşünen, dalgalanmaya dayanıklı, yüksek risk toleranslı yatırımcılar",
  },
];

const STRATEGIES = [
  {
    name: "Düzenli Ortalama Maliyet (DCA)",
    shortDesc: "Belirli aralıklarla düzenli alım yaparak piyasa zamanlaması riskini azaltma",
    icon: "📅",
    description: "DCA (Dollar Cost Averaging), belirli bir varlığı her ay/çeyrek düzenli olarak satın almayı ifade eder. Amaç, fiyat dalgalanmalarından etkilenmeden ortalama bir maliyet yakalamaktır. Piyasa zamanlaması yapmaya çalışmaz.",
    pros: ["Piyasa zamanlaması gerektirmez", "Duygusal kararları azaltır", "Disiplinli birikim sağlar", "Düşüşlerde daha çok, yükselişlerde daha az alır"],
    cons: ["Yükselen piyasada toplu alımdan düşük getiri", "Uzun vadede bağlılık gerektirir", "Her varlık türüne uygun değil"],
    suitableFor: "Uzun vadeli birikim yapan, piyasa takibi yapmak istemeyen yatırımcılar",
    example: "Her ay 5.000 TL ile BIST 100 endeks fonu almak. Fiyat düşükken daha çok, yüksekken daha az pay alınır.",
  },
  {
    name: "Değer Yatırımı",
    shortDesc: "Piyasada düşük değerlenmiş hisseleri bularak uzun vadeli yatırım",
    icon: "🔍",
    description: "Değer yatırımı, piyasa değeri gerçek değerinin altında olan şirketlerin hisselerini satın almayı hedefler. Warren Buffett'ın benimsediği bu strateji, sabır ve detaylı finansal analiz gerektirir.",
    pros: ["Uzun vadede yüksek getiri potansiyeli", "Düşük risk profili (doğru seçilirse)", "Şirketleri anlama gerektirir, bilinçli yatırım"],
    cons: ["Kısa vadede düşük performans", "Kapsamlı analiz gerektirir", "Değer tuzağı riski (ucuz görünen ama düşüşteki hisse)"],
    suitableFor: "Finansal okuryazarlığı yüksek, sabırlı, uzun vadeli yatırımcılar",
    example: "F/K oranı düşük, güçlü bilançosu olan bir BIST 30 şirketini analiz edip uzun vadeli almak.",
  },
  {
    name: "Büyüme Yatırımı",
    shortDesc: "Kârını ve gelirini ortalamanın üzerinde artıran şirketlere yatırım",
    icon: "🚀",
    description: "Büyüme yatırımı, sektör ortalamasının üzerinde büyüyen şirketlerin hisselerine odaklanır. Bu şirketler genellikle kârlarını yeniden yatırıma dönüştürür ve temettü dağıtmaz.",
    pros: ["Yüksek getiri potansiyeli", "Piyasa trendlerinden faydalanma", "Yenilikçi sektörlerde fırsat"],
    cons: ["Yüksek volatilite", "Pahalı değerlemeler (yüksek F/K)", "Büyüme yavaşlarsa sert düşüş"],
    suitableFor: "Yüksek risk toleranslı, sektör trendlerini takip eden yatırımcılar",
    example: "Teknoloji veya yeşil enerji sektöründe hızlı büyüyen bir şirketin hissesine yatırım yapmak.",
  },
  {
    name: "Temettü Yatırımı",
    shortDesc: "Düzenli temettü dağıtan şirketlerden pasif gelir elde etme",
    icon: "💰",
    description: "Temettü yatırımı, düzenli ve istikrarlı temettü dağıtan şirketlerin hisselerine odaklanır. Hem temettü geliri hem de uzun vadede değer artışı hedeflenir.",
    pros: ["Düzenli pasif gelir", "Düşük volatilite (istikrarlı şirketler)", "Bileşik temettü etkisi"],
    cons: ["Sınırlı büyüme potansiyeli", "Temettü kesintisi riski", "Vergi kesintisi (stopaj)"],
    suitableFor: "Düzenli gelir arayan, uzun vadeli, düşük-orta risk profilli yatırımcılar",
    example: "Yıllık düzenli temettü dağıtan BIST şirketlerinden oluşan bir sepete yatırım.",
  },
  {
    name: "Endeks Takibi (Pasif Yatırım)",
    shortDesc: "BIST 100 veya S&P 500 gibi endeksleri birebir takip etme",
    icon: "📊",
    description: "Pasif yatırım, bir endeksi birebir takip eden fon veya ETF alarak piyasa ortalamasını yakalamayı hedefler. Aktif yönetim ücreti düşüktür ve piyasa zamanlaması gerektirmez.",
    pros: ["Düşük yönetim ücreti", "Piyasa ortalamasını yakalar", "Çeşitlendirme sağlar", "Basit ve disiplinli"],
    cons: ["Piyasayı geçemez (ortalamayı alır)", "Düşüşlerde koruma yok", "Sektörel yoğunlaşma riski"],
    suitableFor: "Yatırıma yeni başlayanlar, düşük maliyetli çeşitlendirme arayanlar",
    example: "Her ay BIST 100 endeks fonu alarak Türkiye borsasına pasif yatırım yapmak.",
  },
  {
    name: "Hedge / Riskten Korunma",
    shortDesc: "Portföyü olası düşüşlere karşı koruma stratejisi",
    icon: "🛡️",
    description: "Hedge stratejisi, portföydeki varlıkların değer kaybına karşı VİOP, opsiyon veya döviz gibi araçlarla koruma sağlamayı amaçlar. Kurumsal yatırımcılar ve deneyimli bireyseller için uygundur.",
    pros: ["Portföyü düşüşlere karşı korur", "Belirsizlik dönemlerinde güvence sağlar"],
    cons: ["Koruma maliyeti (prim/komisyon)", "Yükselen piyasada getiriyi sınırlar", "Karmaşık yapı"],
    suitableFor: "Büyük portföy sahipleri, kurumsal yatırımcılar, deneyimli bireyseller",
    example: "Elinizdeki hisse senetlerine karşı BIST 30 VİOP kontratı ile kısa pozisyon alarak portföyü korumak.",
  },
  {
    name: "Kısa Vadeli Alım-Satım (Trading)",
    shortDesc: "Kısa süreli fiyat hareketlerinden kâr elde etme",
    icon: "⚡",
    description: "Trading, gün içi (intraday) veya birkaç günlük pozisyonlarla kısa vadeli fiyat dalgalanmalarından kâr elde etmeyi hedefler. Teknik analiz ve piyasa takibi yoğun olarak kullanılır.",
    pros: ["Kısa sürede kâr potansiyeli", "Piyasa trendlerinden hızlı faydalanma", "Yüksek likidite avantajı"],
    cons: ["Çok yüksek risk", "Yüksek işlem maliyeti (komisyon)", "Duygusal karar riski", "Zaman ve dikkat gerektirir"],
    suitableFor: "Deneyimli, piyasa takibi yapabilen, yüksek risk toleranslı yatırımcılar",
    example: "Gün içinde BIST 30 hisselerinde teknik analiz yaparak kısa pozisyonlarla al-sat yapmak.",
  },
];
